version: '2'
services:
    flask-1:
        build: ./app-http
        command: python /app/app.py
        privileged: true
        volumes:
            - $PWD/app-http:/app
        expose:
            - 8080

    flask-2:
        build: ./app-https
        command: python /app/app.py
        privileged: true
        volumes:
            - $PWD/app-https:/app
        expose:
            - 8081

#    nginx:
#        put your configuration here